name: Run Python Script

on:
  push:
    branches:
      - main # 또는 master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # - name: Install dependencies
      # run: |
        # pip install -r requirements.txt # 필요한 경우

    - name: Run script
      run: python python/gen_files_json.py --outputs json,html . # 실행할 파일명


